"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {defaultContent,type Lang,type SiteContent} from "../site-content";

const langNames:Record<Lang,string>={pl:"Polski",en:"English",ua:"Українська"},uid=()=>crypto.randomUUID();
export default function AdminClient({email,signOutHref}:{email:string;signOutHref:string}){
 const [content,setContent]=useState<SiteContent>(defaultContent),[lang,setLang]=useState<Lang>("pl"),[tab,setTab]=useState("menu"),[status,setStatus]=useState("Ładowanie…"),[saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/content",{cache:"no-store"}).then(async r=>await r.json() as SiteContent).then(d=>{setContent(d);setStatus("Wszystko gotowe")}).catch(()=>setStatus("Błąd pobierania danych"))},[]);
 const update=(fn:(d:SiteContent)=>void)=>{const d=structuredClone(content);fn(d);setContent(d);setStatus("Masz nieopublikowane zmiany")};
 const publish=async()=>{setSaving(true);setStatus("Publikowanie…");try{const r=await fetch("/api/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(content)});if(!r.ok)throw 0;setStatus("Zmiany są już widoczne na stronie")}catch{setStatus("Nie udało się opublikować")};setSaving(false)};
 const upload=async(file:File)=>{setStatus("Wysyłanie zdjęcia…");const form=new FormData();form.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:form});if(!r.ok){setStatus("Nie udało się wysłać zdjęcia");return}const {url}=await r.json() as {url:string};update(d=>d.gallery.push({id:uid(),url,alt:{pl:file.name,en:file.name,ua:file.name},visible:true}))};
 const titles:Record<string,string>={menu:"Menu i ceny",gallery:"Galeria zdjęć",reviews:"Opinie gości",settings:"Nazwa, kontakt i godziny"};
 return <main className="admin-app"><aside className="admin-side"><Link className="admin-brand" href="/">Szablon kawiarni</Link><p>Panel zarządzania</p><nav>{Object.keys(titles).map(k=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{titles[k]}</button>)}</nav><div className="account"><small>Zalogowano jako</small><span>{email}</span><a href={signOutHref}>Wyloguj</a></div></aside><section className="admin-main">
  <header className="top"><div><h1>{titles[tab]}</h1><p>{status}</p></div><div><a href="/" target="_blank">Podgląd ↗</a><button onClick={publish} disabled={saving}>{saving?"Publikuję…":"Opublikuj zmiany"}</button></div></header>
  {tab!=="settings"&&<div className="langs">{(["pl","en","ua"] as Lang[]).map(l=><button key={l} className={lang===l?"active":""} onClick={()=>setLang(l)}>{langNames[l]}</button>)}</div>}
  {tab==="menu"&&<div className="stack">{content.menu.map((cat,ci)=><section className="admin-card" key={cat.id}><div className="card-head"><input className="title-input" value={cat.label[lang]} onChange={e=>update(d=>{d.menu[ci].label[lang]=e.target.value})}/><button className="danger" onClick={()=>update(d=>{d.menu.splice(ci,1)})}>Usuń kategorię</button></div>{cat.items.map((it,ii)=><div className="menu-edit" key={it.id}><input value={it.name[lang]} onChange={e=>update(d=>{d.menu[ci].items[ii].name[lang]=e.target.value})}/><input className="price" value={it.price} onChange={e=>update(d=>{d.menu[ci].items[ii].price=e.target.value})}/><label><input type="checkbox" checked={it.visible} onChange={e=>update(d=>{d.menu[ci].items[ii].visible=e.target.checked})}/>{it.visible?"Widoczne":"Ukryte"}</label><button className="x" onClick={()=>update(d=>{d.menu[ci].items.splice(ii,1)})}>×</button></div>)}<button className="add" onClick={()=>update(d=>d.menu[ci].items.push({id:uid(),name:{pl:"Nowa pozycja",en:"New item",ua:"Нова позиція"},price:"0,00 zł",visible:true}))}>+ Dodaj pozycję</button></section>)}<button className="add-section" onClick={()=>update(d=>d.menu.push({id:uid(),label:{pl:"Nowa kategoria",en:"New category",ua:"Нова категорія"},items:[]}))}>+ Dodaj kategorię</button></div>}
  {tab==="gallery"&&<section className="admin-card"><label className="upload"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><b>+ Dodaj nowe zdjęcie</b><span>JPG, PNG, WEBP lub GIF — maks. 10 MB</span></label><div className="gallery-edit">{content.gallery.map((it,i)=><article key={it.id}><img src={it.url} alt=""/><input value={it.alt[lang]} onChange={e=>update(d=>{d.gallery[i].alt[lang]=e.target.value})}/><div><label><input type="checkbox" checked={it.visible} onChange={e=>update(d=>{d.gallery[i].visible=e.target.checked})}/>{it.visible?"Widoczne":"Ukryte"}</label><button className="danger" onClick={()=>update(d=>{d.gallery.splice(i,1)})}>Usuń</button></div></article>)}</div></section>}
  {tab==="reviews"&&<div className="stack">{content.reviews.map((it,i)=><section className="admin-card review-edit" key={it.id}><input value={it.name} placeholder="Imię autora" onChange={e=>update(d=>{d.reviews[i].name=e.target.value})}/><input type="number" min="1" max="5" value={it.rating} onChange={e=>update(d=>{d.reviews[i].rating=Math.max(1,Math.min(5,Number(e.target.value)))})}/><textarea value={it.text[lang]} onChange={e=>update(d=>{d.reviews[i].text[lang]=e.target.value})}/><input value={it.meta} placeholder="Źródło lub data" onChange={e=>update(d=>{d.reviews[i].meta=e.target.value})}/><div><label><input type="checkbox" checked={it.visible} onChange={e=>update(d=>{d.reviews[i].visible=e.target.checked})}/>{it.visible?"Widoczna":"Ukryta"}</label><button className="danger" onClick={()=>update(d=>{d.reviews.splice(i,1)})}>Usuń opinię</button></div></section>)}<button className="add-section" onClick={()=>update(d=>d.reviews.push({id:uid(),name:"Nowy gość",text:{pl:"Nowa opinia",en:"New review",ua:"Новий відгук"},meta:"",rating:5,visible:true}))}>+ Dodaj opinię</button></div>}
  {tab==="settings"&&<section className="admin-card settings">{Object.entries({brandName:"Nazwa kawiarni",addressLine1:"Adres — linia 1",addressLine2:"Adres — linia 2",phone:"Telefon",instagram:"Link do Instagramu",instagramHandle:"Nazwa na Instagramie",facebook:"Link do Facebooka",googleMapsUrl:"Link do Google Maps (opcjonalnie)",weekdays:"Poniedziałek–piątek",saturday:"Sobota",sunday:"Niedziela"}).map(([k,label])=><label key={k}><span>{label}</span><input value={content.settings[k as keyof SiteContent["settings"]]} onChange={e=>update(d=>{d.settings[k as keyof SiteContent["settings"]]=e.target.value})}/></label>)}</section>}
 </section></main>;
}
